### ISSUE TITLE
Gitignore improvement

### ISSUE THREAD

**Issue by dianjuar** [Villanuevand/angular2-forms#8]
Hola.
Creo que tu gitignore se puede mejorar utilizando el de [gitignore.io](https://www.gitignore.io/api/angular)

Vi que no ignoras la carpeta `Typings` a pesar de que en tu `package.json` cuando instalas el repo usando `npm install` tienes el comando post instalación `"postinstall": "typings install"`. Así que no tiene ningún sentido tener en el repo la carpeta typings.
También queda más bonito ;).

Btw, si me puedes indicar de donde sacaste el seed project

**Comment by Villanuevand** [comment]
Hola, @dianjuar 

¿Cómo te va? Mil gracias por tu recomendación, en cuanto tenga un tiempo libre la llevo a cabo, en caso de que ya lo hayas solucionado te invito a hacer el `pull request`  y con gusto lo mergeo 

El seed lo saque de la organzación de [Angular](https://github.com/angular/)
Se llama [Angular2-seed](https://github.com/angular/angular2-seed)

**Comment by dianjuar** [comment]
Justamente estaba buscando un seed y me topé con este. Analizándolo me di cuenta del gitignote.

El [Angular2-seed](https://github.com/angular/angular2-seed) lo había visto lo veo too noisy for a newbie

**Comment by Villanuevand** [comment]
@dianjuar : Si te soy sincero tengo mucho que no veo algún seed, ya que estoy usando`angular-cli` que es bastante más cómodo para trabajar, pero si tu skills, es de novato, puede costar un poco de entender toda la magia que este genera.

Pero te invito a mirar el proyecto =>  [angular-cli](https://github.com/angular/angular-cli). 

¡Quedo muy atento de tus comentarios!

**Comment by dianjuar** [comment]
Hola @Villanuevand.
le eché un vistazo a `angular-cli`... Eso explica el porque no hay seed projects de angular por ahí.

Tengo como una lista mental de las cosas por aprender y `angular-cli` tenía prioridad baja, por tu comentario la adelanté. Ahora que se de que va el asunto, asumo que el profesor del curso que estoy tomando cuando impartió el curso no estaba desarrollado `angular-cli` porque está ESTA SUPER!, facilita mucho mucho mucho muchisimo las cosas.
